<header class="header" id="head">  
    <h1><a href="?route=home" aria-label="Lien vers la page d'accueil">Style africain</a></h1>
    <nav id="header-admin-menu">
        <ul class="menu-list">
            <li class="menu-item"><a href="?route=home">Accueil</a></li>
            <li class="menu-item"><a href="?route=boutique">Boutique</a></li>
            <li class="menu-item"><a href="?route=apropos">À propos</a></li>

            <?php if(isset($_SESSION["user"])) :?>
                <li class="menu-item"><a href="?route=deconnexion">Déconnexion</a></li>
            <?php else :?>
                <li class="menu-item"><a href="?route=login">Connexion</a></li>
                <li class="menu-item"><a href="?route=register">Compte</a></li>

            <?php endif;?>
            <li class="menu-item"><a href="mailto:ahodomed@gmail.com" target="_blank">Contact</a></li>
        </ul>
        <div id="icons"></div>
    </nav>
</header>



