<header id="yep-head">  
           <body>
    <h1>Style africain</h1>
    <nav>
        <ul>
            <li><a href="index.php?route=login">Se connecter</a></li>
            <li><a href="index.php?route=register">Créer un compte</a></li>
            <li><a href="">Accueil</a></li>
            <li><a href="index.php?route=boutique">Boutique </a></li>
           

        </ul>
    </nav>
    
</header>


