<header id="yep-head">  
            <nav>  
                <h1>E-techMax</h1> 
                <a href=""><img src="" alt="logo"></a>  
                <ul>  
                    <li>  
                        <a href="index.php?route= ">Accueil</a> 
                    </li>  
                    <li>  
                        <a href="index.php?route=détail-product">Produits</a>  
                    </li>
                    <li>  
                        <a href="index.php?route=deconnexion">Déconnexion</a>  
                    </li>  
                    <li>
                         <a href="index.php?route=create-product">creer un produit </a>
                    </li>
                    <li>
                        <a href="index.php?route=edit-user">Modifier le compte</a>
                    </li>

                </ul>  
            </nav>  
</header>