<main id="connect">  
    <h2>Connexion</h2> 
    
    <?php
    
    //var_dump($data['error']);
        if(!empty($data['error']))
        
            echo "<p class='errors-message'>". $data["error"][0]. "</p>";
    ?>
    <form method="post" action="?route=login" class="connect">  
        <input type="hidden" name="loginForm" value="login" class="loginForm">  
        <fieldset id="fieldco">  
            <label for="email-log">  
                Email  
            </label>  
            <input type="email" name="email" id="email-log" class="connex" required>  
            <label for="password">  
                Mot de passe  
            </label>  
            <input type="password" name="password" id="password-log" class="connex" required>  
        </fieldset>  
        <button type="submit" class="btnlog" aria-label="Bouton de connecxion">Se Connecter</button>  
         <a href="?route=register" aria-label="Lien vers la page de connexion">vous n'avez pas encore de compte?</a>

        
    </form>
</main>
