<main id="connect">  
    <h2>Connexion</h2>  
    <form method="post" action="?route=login" class="connect">  
        <input type="hidden" name="formName" id="formName" value="loginForm" class="connex">  
        <fieldset id="fieldco">  
            <label for="email-log">  
                Email  
            </label>  
            <input type="email" name="email" id="email-log" class="connex" required>  
            <label for="password">  
                Mot de passe  
            </label>  
            <input type="password" name="password" id="password-log" class="connex" required>  
        </fieldset>  
        <button type="submit" class="btnlog">Se Connecter
        </button>  
    </form>
   
    </main>
