<main class="main-create-product">
    <h2>Ajouter un Produit</h2>
    <form action="?route=create-product" method="post">
        <label for="name">Nom du produit :</label>
        <input type="text" name="name" id="name" required>
        
        <label for="description">Description :</label>
        <textarea name="description" id="description"></textarea>
        
        <label for="price">Prix :€</label>
        <input type="text" name="price" id="price" required>
        
        <label for="product-category">Choississez la categorie :</label>
        <select name="product-category">
            <option value="3">Hommes</option>
            <option value="2">Femmes</option>
            <option value="1">Accessoires</option>
            <option value="4">Enfants</option>


        </select>
        
        <h3> Ajouter un média</h3>

        <label for="media-name">Name :</label>
        <input type="text" name="media-name"/>
        <label for="media-url">Url :</label>
        <input type="text" name="media-url">
        <input type="hidden" name="createProduct" value="submit">
        <fieldset aria-label="boutton de création d'un article">
            <button type="submit" aria-label="boutton de création d'article">Créer l'article</button>
        </fieldset>
    </form>
</main>
