<main id="detail"> 
    <h2 class="sr-only">Liste Des Produits</h2>
        <?php
        foreach($data['products'] as $product)
        { ?>
        <article>
            <header>
                <h3 class=""><?= $product->getName(); ?></h3>  
            </header>
            <figure>
                <img src=""<?= $product->getMediaId(); ?> alt="l'image en présentation">
            </figure>
         </article>
        
     <?php } ?>
     
</main>  