<h2 class="list">Liste Des Produits</h2>

<main id="article-list"> 

    <?php
    foreach($data['productsWithMedias'] as $product)
    { ?>
            <article>
                <a href="/afrostyle/index.php?route=detail-product&id=<?= $product->getId(); ?>" aria-label="lien vers la page détail produit" >

                    <header>
                        <h3 class=""><?= $product->getName(); ?></h3>  
                    </header>
                
                    <?php foreach($product->getMedia() as $media) :?>
                        <img src="<?= $media->getUrl() ?>" alt="<?= $media->getName() ?>">
                    <?php endforeach; ?>
                </a>

            </article>
    <?php } ?>
</main>
