<main id="detail"> 
    <h2 class="sr-only">Détail du produit</h2>
        <?php $product = $data['product'];
        $media = $product->getMedia();
        ?>
        <article>
            <header>
                <h3 class="titre-article"><?= $product->getName() ?></h3>  

            </header>
            <figure class="left">
                <img src="<?= $media[0]->getUrl() ?>" alt="<?= $media[0]->getName()?>" alt="image du produit">
            </figure>
          
                <p><?= $product->getDescription()?></p>
                <p><?= $product->getPrice() ?>€</p>
            
              <a href="?route=contact&id=<?= $product->getId()?>" target="_blank" aria-label="lien d'envoi de mail pour commander un produit">Contacter-nous pour commander</a>
                           
             <a href='?route=boutique' aria-label="lien de retour sur la page boutique">Retour</a>

         </article>
       
     
</main>  