<main id="edit-user" class="admin-form"> 
    <h3>Modifier un utilisateur</h3>
    <p class="form-errors">
    <?php
        if(isset($data['errors']))
            echo $data["errors"][0];
    ?>
    </p>
    <?php $user = $data['user'];?>
    <form action="?route=edit-user&id=<?= $_GET['id'] ?>" method="post">
        <fieldset>
            <label for="edit-username"> Nom d'utilisateur </label>
            <input type="text" name="edit-username" id="edit-username" value="<?= $user->getUsername() ?>"/>
        </fieldset>
        <fieldset>
            <label for="edit-email"> Email </label>
            <input type="email" name="edit-email" id="edit-email" value="<?= $user->getEmail() ?>"/>
        </fieldset>
        <fieldset>
            <label for="edit-password"> Mot de passe </label>
            <input type="password" name="edit-password" id="edit-password" />
        </fieldset>
        <fieldset>
            <label for="edit-confirm-password"> Confirmer le mot de passe </label>
            <input type="password" name="edit-confirm-password" id="edit-confirm-password"/>
        </fieldset>
        <fieldset>
            <label for="edit-roleId"> Modifier le rôle </label>
            <?php if($user->getRole() == "1") : ?>
                <select name="edit-roleId" id="edit-roleId">
                    <option value="1">User</option>
                    <option value="2">Admin</option>
                </select>
            <?php else : ?>
                <select name="edit-roleId" id="edit-roleId">
                    <option value="2">Admin</option>
                    <option value="1">User</option>
                </select>
            <?php endif; ?>
        </fieldset>
        <fieldset>
            <button type="submit"> Modifier le compte </button>
        </fieldset>
         <input type="hidden" name="edit-form" value="edit"/>
    </form>
</main>
