 <header>
        <nav>
              <ul>
                <li><a href="index.php?route=admin-user">Utilisateurs</a></li>
                <li><a href="index.php?route=admin-produits">Produits</a></li>
                <li><a href="index.php?route=admin-categories">Categories</a></li>
                <li><a href="">Retour au site</a></li>
              </ul>
            </nav>
</header>
        <?php require "{$page}.phtml"; ?>  
        <footer id="">  
            <ul>
              <li><a href="mentions-legales.html">Mentions légales</a></li>
              <li><a href="contact.html">Contact</a></li>
              <li><a href="https://www.facebook.com/">Facebook</a></li>
              <li><a href="https://www.instagram.com/">Instagram</a></li>
              <li><a href="https://www.linkedin.com/">LinkedIn</a></li>
            </ul>  
        </footer>  
    </body>  
</html>