<footer class="foot" id="foot">  
            <ul>
            <li class="menu-item"><a href="mailto:ahodomed@gmail.com" target="_blank">Contact</a></li>
            <li><a href="https://www.linkedin.com/">LinkedIn</a></li>
              <li><a href="https://www.facebook.com/">Facebook</a></li>
              <li><a href="https://www.instagram.com/">Instagram</a></li>
              <li><a href="?route=mentions-legales">Mentions légales</a></li>

            </ul>
</footer> 


