<footer class="foot" id="foot">  
            <ul>
              <li><a href="#">Mentions légales</a></li>
              <li><a href="#">Contact</a></li>
              <li><a href="https://www.facebook.com/">Facebook</a></li>
              <li><a href="https://www.instagram.com/">Instagram</a></li>
              <li><a href="https://www.linkedin.com/">LinkedIn</a></li>
            </ul>
</footer> 


