<footer class="foot" id="foot">  
            <ul>
              <li class="menu-item"><a href="mailto:ahodomed@gmail.com" target="_blank" aria-label=" lien contact pour envoi de mail">Contact</a></li>
              <li><a href="https://www.linkedin.com/" aria-label="Lien vers notre page LikedIn">LinkedIn</a></li>
              <li><a href="https://www.facebook.com/" aria-label="Lien vers notre page facebook">Facebook</a></li>
              <li><a href="https://www.instagram.com/" aria-label="Lien vers notre page Instagram">Instagram</a></li>
              <li><a href="?route=mentions-legales" aria-label="Lien vers les mentions legales">Mentions légales</a></li>

            </ul>
</footer> 


