<section id="section-g">  
    <section class="legales">
       <h5>
           Mentions Légales

1. Informations légales

Ce site web est la propriété de [Nom de l'entreprise ou de l'individu]
Adresse : [Adresse légale de l'entreprise]
Téléphone : [Numéro de téléphone]
Email : [Adresse e-mail de contact]

Numéro SIRET : [Numéro SIRET de l'entreprise]
RCS : [Numéro RCS de l'entreprise]
TVA intracommunautaire : [Numéro de TVA intracommunautaire de l'entreprise]

Directeur de la publication : [Nom du directeur de la publication]

2. Hébergement

Ce site web est hébergé par [Nom de l'hébergeur]
Adresse : [Adresse de l'hébergeur]
Téléphone : [Numéro de téléphone de l'hébergeur]
Email : [Adresse e-mail de l'hébergeur]

3. Propriété intellectuelle

Le contenu de ce site web, y compris les textes, images, vidéos et autres éléments multimédias, est protégé par les lois sur la propriété intellectuelle. Tous les droits de reproduction, de représentation et de diffusion sont réservés.

4. Collecte de données personnelles

Ce site peut collecter des données personnelles dans le cadre de ses activités. Les données collectées seront utilisées uniquement à des fins spécifiques et ne seront pas transmises à des tiers sans le consentement explicite de la personne concernée.

5. Cookies

Ce site web utilise des cookies pour améliorer l'expérience de l'utilisateur. En naviguant sur ce site, vous acceptez l'utilisation de cookies conformément à notre politique en matière de cookies.

6. Responsabilité

L'utilisation de ce site web est de la responsabilité de l'utilisateur. L'entreprise [Nom de l'entreprise] ne saurait être tenue responsable des dommages directs ou indirects résultant de l'utilisation de ce site web.

7. Contact

Pour toute question ou préoccupation concernant ces mentions légales, veuillez nous contacter à l'adresse e-mail suivante : [Adresse e-mail de contact].

Date de dernière mise à jour : [Date de la dernière mise à jour des mentions légales]


       </h5>
    </section>

</section>
