
    <h2>Contactez-nous</h2>
    <form action="" method="post" class="contact">
        <label for="nom">Nom :</label>
        <input type="text" id="nom" name="nom" required>
        
        <label for="email">Adresse Email :</label>
        <input type="email" id="email" name="email" required>
        
        <label for="sujet">Sujet :</label>
        <input type="text" id="sujet" name="sujet" required>
        
        <label for="message">Message :</label>
        <textarea id="message" name="message" rows="4" required></textarea>
        
        <input type="submit" value="Envoyer">
        <a href='?route=home'>Retour </a>

    </form>
