
<main class="main-contact">
    <h2>Formulaire de Message</h2>
        
        <?php
        /*
        if (isset($data['errors'])) {
          echo "<p class='errors-message'>" . $data["errors"][0] . "</p>";
        }
        */
        ?>

                 
    <form action="?route=contact&id=<?= $_GET['id'] ?>" method="POST">
        <label for="name">Nom :</label>
        <input type="text" name="name" id="name" required>

        <label for="email">Email :</label>
        <input type="email" name="email" id="email" required>

        <label for="message">Message :</label>
        <textarea name="message" id="message" rows="4" required></textarea>

        <input type="hidden" name="contact-form" value="submit"/>
        
        <input type="submit" value="Envoyer">
    </form>
            <!--<script src="/afrostyle/assets/styles/js/validation-pass.js"></script>-->

</main>
