<section id="section-g">  
    <section class="section-h">
        <a href="/afrostyle/index.php?route=detail-category&id=1" alt="Collection homme">
            <img src="./assets/images/hommes/homme3.jpeg" style="width: 100%; max-width: 300px; height: auto;">
            Collection homme
        </a>
    </section>
   
    <section class="section-f">
        <a href="/afrostyle/index.php?route=detail-category&id=2" alt="Collection femme">
            <img src="./assets/images/femmes/femme1.jpeg" style="width: 100%; max-width: 300px; height: auto;">
            Collection femme
        </a>
    </section>
    <section class="section-e">
        <a href="/afrostyle/index.php?route=detail-category&id=4" alt="Collection enfant">
            <img src="./assets/images/enfants/enfant1.jpg" style="width: 100%; max-width: 300px; height: auto;">
            Collection enfant
        </a>
    </section>
    <section class="section-a">
        <a href="/afrostyle/index.php?route=detail-category&id=3" alt="Collection accessoires">
            <img src="./assets/images/accessoires/accessoire4.png" style="width: 100%; max-width: 300px; height: auto;">
            Accessoires
        </a>
    </section>
</section>
