<main id="a-main">
<section class="section-m" id="accueil">

    <h1 class="a-title">Bienvenu sur Afrostyle</h1>
    <?php if(isset($data["message"])) {
            echo $data["message"][0];
            }?>
    <h2>Nos nouveaux produits</h2> 

    <section id="section-g">  
        <section class="section-h">
                 <a href="" alt="Collection accessoires"><img src="./assets/styles/images/hommes/homme3.jpeg">collection homme</a>
        </section>
       
        <section class="section-f">
                <a href="" alt="Collection femme"><img src="./assets/styles/images/femmes/femme1.jpeg">Collection femme</a>
    
        </section>
        <section class="section-e">
                  <a href="" alt="Collection enfant"><img src="./assets/styles/images/enfants/enfant1.jpg">Collection enfant</a>
    
        </section>
        <section class="section-a">
                  <a href="" alt="Collection accessoires"><img src="./assets/styles/images/accessoires/accessoir2.jpg">accessoires</a>
    
        </section>
     </section>
</section>
</main>
