<main id="main-homepage">  
    <div class="search-bar">
        <input type="text" id="searchInput" placeholder="Rechercher un produit">
        <button id="searchButton">Rechercher</button>
    </div>
    <h2> Nos Différentes collections</h2>
    <section class="section-h">
            <a href="/afrostyle/index.php?route=detail-category&id=3">
            <img src="./assets/images/hommes/homme3.jpeg" alt="images illustrant le contenu de la catégorie homme">
           <h3>Collection homme</h3> 
        </a>
    </section>
   
    <section class="section-f">
        <a href="/afrostyle/index.php?route=detail-category&id=2">
            <img src="./assets/images/femmes/femme1.jpeg" alt="images illustrant le contenu de la catégorie femme">
            <h3>Collection femme</h3> 
        </a>
    </section>
    <section class="section-e">
        <a href="/afrostyle/index.php?route=detail-category&id=4">
            <img src="./assets/images/enfants/enfant1.jpg" alt="images illustrant le contenu de la catégorie enfant">
            <h3>Collection enfant</h3> 

        </a>
    </section>
    <section class="section-a">
            <a href="/afrostyle/index.php?route=detail-category&id=1">
            <img src="./assets/images/accessoires/accessoire4.png" alt="images illustrant le contenu de la catégorie accessoire">
            <h3>Collection Accessoires</h3> 

        </a>
    </section>
            <script src="/afrostyle/assets/styles/js/search-bar.js"></script>

</main>
