<main id="a-main">
<section id="accueil">
    <h2 class="a-title">Bienvenu sur Afrostyle</h2>
</section>
    <section id="section-g">  
        <h2>Nos nouveaux produits</h2> 
    <section class="section-h">
             <a href="" alt="Collection accessoires"><img src="./assets/styles/images/hommes/homme3.jpeg">collection homme</a>

    </section>
    <section class="section-f">
            <a href="" alt="Collection femme"><img src="./assets/styles/images/femmes/femme1.jpeg">Collection femme</a>

    </section>
    <section class="section-a">
              <a href="" alt="Collection enfant"><img src="./assets/styles/images/enfants/enfant1.jpg">Collection enfant</a>

    </section>
    <section class="section-h">
              <a href="" alt="Collection accessoires"><img src="./assets/styles/images/accessoires/accessoir2.jpg">accessoires</a>

    </section>
</section>
</main>
