<!DOCTYPE html>  
<html lang="fr">  
    <head>  
        <meta charset="utf-8">  
        <link rel="stylesheet" href="./assets/styles/css/style.css" />

               <title>Style africaine</title>  

    </head>  
    <body id="body">
        
        <?php
        if(isset($_SESSION["role"]) && $_SESSION["role"] === 2){
            
            require "admin/partials/_admin_header.phtml";
        }
        else{
            require "header/header.phtml";
        }
        ?>
        
                <?php require "{$page}.phtml";
                 require "footer/footer.phtml";

                ?>
       
    </body>
</html>
