<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/styles/css/reset.css">
    <link rel="stylesheet" href="./assets/styles/css/style.css">


    <title>Style Africain</title>  </head>
  <body>
     
        <?php
            if(isset($_SESSION["role"]) && $_SESSION["role"] === 2){
                
                require "admin/partials/_admin_header.phtml";
            }
            else{
                require "header/header.phtml";
            }
        ?>
        
                <?php require "{$page}.phtml";
                     require "footer/footer.phtml";

                ?>
       
    </body>
         <script src="/afrostyle/assets/styles/js/toggle-menu.js"></script>
        <script src="/afrostyle/assets/styles/js/validation-pass.js"></script>

   
    

</html>



