<main id="main-categoyep"> 
    <h2>Les produits de la catégorie <?= $data['category'] ?></h2> 
  
            <?php 
            foreach ($data['products'] as $product)
            { ?>  
        <article>
            <header>  
                <h3><?= $product->getName() ?></h3>  
            </header>  
            <p>  
                <?= $product->getDescription() ?>  
            </p>  
            <figure aria-label="image représentant une categorie">
                <img src="<?= $product->getMedia(); ?>" alt="photo représentant cette catégorie">
            </figure>
             
        </article>  
        <?php } ?>
</main>  

